version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh
    networks:
      - app-network
    command: ["/bin/sh", "/start-ollama.sh"]

volumes:
  ollama-data:

networks:
  app-network:
    driver: bridge
