services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env

  backend:
    image: copilot-api
    container_name: copilot-api
    ports:
      - "9999:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
