version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
